### ISSUE TITLE
Generator should give error when submessage with callbacks is used inside oneof

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nanopb/nanopb#148]
```
What steps will reproduce the problem?
1. Create a message with callback fields.
2. Put said message inside another message's oneof field.
3. Run generator and try to decode the message.
4. Generator does not complain but decoding will not work properly.

What is the expected output? What do you see instead?
Generator should give an error as callback fields cannot work inside union.



```

Original issue reported on code.google.com by `Petteri.Aimonen` on 7 Mar 2015 at 8:06

**Comment by danielotero** [comment]
May I ask why callback fields cannot work inside an union?
I have a `repeated` field inside a `message` in an `oneof` field, and the callback to decode it gets erased and I can't decode the actual data.

**Comment by PetteriAimonen** [comment]
In oneof, there is space allocated only to store one of the subfields. So if multiple subfields had callbacks, those callback pointers would overlap and corrupt each other.

One way to resolve this would be to allow "generator time callbacks". This is something I have considered for a while. Instead of setting the callback at runtime, the generator would create the prototypes:
bool MyMessage_myfield_decode_callback(...);
bool MyMessage_myfield_encode_callback(...);
and the function pointers would go into pb_field_t. This way there is no need to store them in the message structure, avoiding the trouble with oneofs. However, it would also mean that you cannot use different callback functions in different situations. This would probably be an option alongside the current callbacks.

If that sounds like it could resolve your problems, feel free to file a separate issue/feature request.
