### ISSUE TITLE
Could add a option to limit maximum width of 80 or 128  and use tab

### ISSUE THREAD

**Issue by swchen44** [nanopb/nanopb#202]
For some reason, the xxx.pb.c and xxx.pb.h can be generator in compile time.

But the source code server will check the coding rule (linux kernel style), 
Could add a option to reduce  linux width to 128  and use tab in pb.c and pb.h  in pb generator ?

Thanks

**Comment by PetteriAimonen** [comment]
Nope, autogenerated files are only meant to be read, not edited. So tab vs. space shouldn't matter for any practical purpose. So I don't consider it worth the maintenance needed to support such a feature.

Maybe just add .pb.c and .pb.h to some "exclude" or "ignore" list in your code style checker? Otherwise I guess you can just use a separate program to convert the style, such as `sed` or `indent`.
