### ISSUE TITLE
 proto3 protobuf files missing has_<fieldname> since 0.3.7

### ISSUE THREAD

**Issue by labishrestha** [nanopb/nanopb#275]
With 0.3.6, when I generate .c/.h with syntax = "proto3"; each generated struct member has a matching has_<fieldname> field. 

Version 0.3.7 and above doesn't generate the matching has_<fieldname> field for any of the fields. Seems like this is bug.

**Comment by PetteriAimonen** [comment]
This matches how proto3 syntax should work, for example Google's own implementation doesn't track the field presence for proto3 either. Instead any field that has a value different from 0 is considered present. I'm not a big fan of this, but it is how proto3 works.

To force proto2 behaviour (i.e. all that existed before 0.3.7), one can specify `* proto3:false` in .options file. But this option only works since 0.3.8.
