### ISSUE TITLE
Bug or Inconsistency with protobuf while encoding "uint32" datatype

### ISSUE THREAD

**Issue by Shams1363** [nanopb/nanopb#288]
Hi,
I have a nested message which is set by nanopb, and I use python-protobuf on the other side to read the data. It has been works most of the times and python is able to read it properly. However, with some specific values, python-protobuf fails to read while nanopb is still able to decode the encoded data. I created a small example and attached to this email. I simply encode two instances of one struct and save them into two different files. It is able to decode one of them but not the other one. I realized that the problem appears when the value of that "varint" passes 128. In that case, it throws an exception message of "google.protobuf.message.DecodeError: Truncated message."
[nanopb_example.tar.gz](https://github.com/nanopb/nanopb/files/1342730/nanopb_example.tar.gz)

**Comment by PetteriAimonen** [comment]
Hmm, the issue seems to be that you write extra zeros to the end of the message, which the Python implementation doesn't handle.

          /// Set the remainder of message to zeros.
          memset(buffer+postream.bytes_written, 0, length - postream.bytes_written);

Instead, you should only write `postream.bytes_written` bytes to the output file.

Though I'm not sure why the "good" file works on the Python side either. It seems that adding one extra '\x00' at the end of the "bad" file makes it also work, so it's probably some subtle issue in Python's parsing.

But anyway, ignoring trailing 0x00 is not a general protobuf feature so you'll need to frame the message otherwise. Nanopb currently silently ignores trailing 0x00, but this functionality will be separated to make it more consistent with other protobuf implementations (issue #278).
