### ISSUE TITLE
Undefined symbols for architecture

### ISSUE THREAD

**Issue by fthuin** [nanopb/nanopb#393]
Hello,
I'm getting an error while building my project (iOS application) with Xcode 10.2.1. I never had this error before (the project is ~1 year old).

```
Ld /Users/fthuin/Library/Developer/Xcode/DerivedData/myproject-ezsfqzsknxmnkphdnsnekleddfjl/Build/Products/Debug-iphoneos/nanopb/nanopb.framework/nanopb normal arm64 (in target: nanopb)
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk -L/Users/fthuin/Library/Developer/Xcode/DerivedData/myproject-ezsfqzsknxmnkphdnsnekleddfjl/Build/Products/Debug-iphoneos/nanopb -F/Users/fthuin/Library/Developer/Xcode/DerivedData/myproject-ezsfqzsknxmnkphdnsnekleddfjl/Build/Products/Debug-iphoneos/nanopb -filelist /Users/fthuin/Library/Developer/Xcode/DerivedData/myproject-ezsfqzsknxmnkphdnsnekleddfjl/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build/Objects-normal/arm64/nanopb.LinkFileList -install_name @rpath/nanopb.framework/nanopb -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/fthuin/Library/Developer/Xcode/DerivedData/myproject-ezsfqzsknxmnkphdnsnekleddfjl/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build/Objects-normal/arm64/nanopb_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/fthuin/Library/Developer/Xcode/DerivedData/myproject-ezsfqzsknxmnkphdnsnekleddfjl/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build/Objects-normal/arm64/nanopb_dependency_info.dat -o /Users/fthuin/Library/Developer/Xcode/DerivedData/myproject-ezsfqzsknxmnkphdnsnekleddfjl/Build/Products/Debug-iphoneos/nanopb/nanopb.framework/nanopb
```
```
Undefined symbols for architecture arm64:
  "_pb_field_iter_begin", referenced from:
      _pb_decode_noinit in pb_decode.o
      _pb_message_set_to_defaults in pb_decode.o
      _pb_release in pb_decode.o
      _iter_from_extension in pb_decode.o
      _pb_encode in pb_encode.o
      _pb_check_proto3_default_value in pb_encode.o
  "_pb_field_iter_find", referenced from:
      _pb_decode_noinit in pb_decode.o
      _pb_release_union_field in pb_decode.o
  "_pb_field_iter_next", referenced from:
      _pb_decode_noinit in pb_decode.o
      _find_extension_field in pb_decode.o
      _pb_message_set_to_defaults in pb_decode.o
      _pb_release in pb_decode.o
      _pb_encode in pb_encode.o
      _pb_check_proto3_default_value in pb_encode.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
It does the same with other platforms (at least x86_64).

Structure of `/Users/fthuin/Library/Developer/Xcode/DerivedData/myproject-ezsfqzsknxmnkphdnsnekleddfjl/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/nanopb.build`:

```
sirius:nanopb.build fthuin$ tree
.
├── DerivedSources
│   └── nanopb_vers.c
├── Objects-normal
│   └── arm64
│       ├── nanopb-dummy.d
│       ├── nanopb-dummy.dia
│       ├── nanopb-dummy.o
│       ├── nanopb.LinkFileList
│       ├── nanopb_vers.d
│       ├── nanopb_vers.dia
│       ├── nanopb_vers.o
│       ├── pb_decode.d
│       ├── pb_decode.dia
│       ├── pb_decode.o
│       ├── pb_encode.d
│       ├── pb_encode.dia
│       └── pb_encode.o
├── all-product-headers.yaml
├── module.modulemap
├── nanopb-all-non-framework-target-headers.hmap
├── nanopb-all-target-headers.hmap
├── nanopb-generated-files.hmap
├── nanopb-own-target-headers.hmap
├── nanopb-project-headers.hmap
└── nanopb.hmap
```

Structure of ` /Users/fthuin/Library/Developer/Xcode/DerivedData/myproject-ezsfqzsknxmnkphdnsnekleddfjl/Build/Products/Debug-iphoneos/nanopb` : 

```
sirius:nanopb fthuin$ tree
.
└── nanopb.framework
    ├── Headers
    │   ├── nanopb-umbrella.h
    │   ├── pb.h
    │   ├── pb_common.h
    │   ├── pb_decode.h
    │   └── pb_encode.h
    └── Modules
        └── module.modulemap
```

**Comment by PetteriAimonen** [comment]
It looks like `pb_common.c` is not included in your project file.

**Comment by fthuin** [comment]
@PetteriAimonen You are right, `pb_common.c` is not included in my Pods, could it mean that the latest Pod release is missing a file?

**Comment by PetteriAimonen** [comment]
I don't know either, I don't use Firebase or pods and I don't know who is maintaining them.

**Comment by trcarden** [comment]
@PetteriAimonen : This is is craaaaazy! nanopb is a dependency for the Firebase CORE library. Like every single person trying to use Flutter + Firebase on iOS (if I am right) will hit this right now.

I bet $5 bucks that the only reason why few people have gotten this far is because Flutter is like 10 abstraction levels above this issue and people trying flutter don't know how any of the machinery works.

In any case let me see if I can figure out how to get the right people involved to fix it

## Apendix

For reference and maybe SEO

1. Here is the Google docs where most normal people will start their journey: https://firebase.google.com/docs/analytics/ios/start

![image](https://user-images.githubusercontent.com/460530/61023226-df96d180-a35d-11e9-8ffa-3a2946b60ae3.png)

2. Even if you don't install the Analytics package you will get it via the FirebaseBase ... Core Pod usually https://github.com/CocoaPods/Specs/blob/master/Specs/0/3/5/Firebase/6.4.0/Firebase.podspec.json

![image](https://user-images.githubusercontent.com/460530/61023177-ac544280-a35d-11e9-9cc8-fe42abdd9787.png)

3. This brings us to the Firebase Analytics Pod which somehow is a dependency of Core (bad Google) is defined here: https://github.com/CocoaPods/Specs/blob/master/Specs/e/2/1/FirebaseAnalytics/6.0.3/FirebaseAnalytics.podspec.json.

![image](https://user-images.githubusercontent.com/460530/61023200-c857e400-a35d-11e9-8131-ff7e371edcb9.png)

4. Finally that lands us here https://cocoapods.org/pods/nanopb and the Maintainer `Jiayong Ou`

![image](https://user-images.githubusercontent.com/460530/61023360-7cf20580-a35e-11e9-8039-eba3a789deb0.png)

5. However after it turns out that is a lie and the real maintainer at Google is... @rsgowman or @paulb777

https://github.com/google/nanopb-podspec 
and his (likely) broken pubspec file:

https://github.com/google/nanopb-podspec/blob/master/nanopb/0.3.9.1/nanopb.podspec

(missing the file in question `pb_common.c` in the sources)

![image](https://user-images.githubusercontent.com/460530/61023487-0dc8e100-a35f-11e9-991e-af2441d44ede.png)

I will file a ticket against that pubspec to see if they can investigate

**Comment by trcarden** [comment]
@PetteriAimonen My mistake, it was simply a bad cache and with the cocoa pods system.

If anyone else runs into this you can simply:

1. `rm -rf Pods`
2. `pod install --verbose`
3.  Get something like this
```
> Copying nanopb from `[redacted]Library/Caches/CocoaPods/Pods/Release/nanopb/0.3.901-2901f` to `Pods/nanopb`
  - Running pre install hooks
```
4. Simply destroy that bad cache `rm [redacted]Library/Caches/CocoaPods/Pods/Release/nanopb/0.3.901-2901f`
5. Then destroy your pods and rerun `pod install --verbose` to get a fresh pull
![image](https://user-images.githubusercontent.com/460530/61025679-47e9b100-a366-11e9-8993-913bc699bc00.png)

According to the pubspec those files should be in there.

**Comment by pk359** [comment]
> @PetteriAimonen My mistake, it was simply a bad cache and with the cocoa pods system.
> 
> If anyone else runs into this you can simply:
> 
> 1. `rm -rf Pods`
> 2. `pod install --verbose`
> 3. Get something like this
> 
> ```
> > Copying nanopb from `[redacted]Library/Caches/CocoaPods/Pods/Release/nanopb/0.3.901-2901f` to `Pods/nanopb`
>   - Running pre install hooks
> ```
> 
> 1. Simply destroy that bad cache `rm [redacted]Library/Caches/CocoaPods/Pods/Release/nanopb/0.3.901-2901f`
> 2. Then destroy your pods and rerun `pod install --verbose` to get a fresh pull
>    ![image](https://user-images.githubusercontent.com/460530/61025679-47e9b100-a366-11e9-8993-913bc699bc00.png)
> 
> According to the pubspec those files should be in there and the linker will find it and everything should work.

Yes works.
