### ISSUE TITLE
Coverity issue: "Dereference after null check" at file pb_encode.c

### ISSUE THREAD

**Issue by jsantana-broadsoft** [nanopb/nanopb#436]
Hello,

We run Coverity analysis tool in our code base and a Dereference after null check issue was reported in file pb_encode.c file.

I am attaching a screenshot of the issue details from the Coverity tool. I hope it provides enough details.

![image](https://user-images.githubusercontent.com/13836740/66230089-ff157000-e6a8-11e9-8935-cac221cc9780.png)

And this is a screenshot of the "details" mentioned in the the previous screenshot (red label at line 379):
![image](https://user-images.githubusercontent.com/13836740/66230245-5f0c1680-e6a9-11e9-8d85-7d6f2d8daa70.png)

**Comment by PetteriAimonen** [comment]
That would only occur if user code sets a repeated field with FT_POINTER to NULL, while passing non-0 size. E.g.

    msg.ptr_array = NULL
    msg.ptr_array_count = 1

In my opinion, that is an user code error.

It could make sense to make the logic so that static analysis tool can follow it, but considering how different it is in current master branch, I don't think it makes sense to modify 0.3 maintenance for just analysis purposes.
