### ISSUE TITLE
C++ interface

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nanopb/nanopb#46]
```
It might be nice to provide an optional C++ interface for the generated 
structures. These would be mostly simple wrapper methods, like

void set_foo(int value) { foo = value; has_foo = true; }

This would provide easier porting to/from Google-official C++ interface.

It should probably be enabled with an option to the generator, in order not to 
pollute the C headers with unnecessary #ifdefs.

```

Original issue reported on code.google.com by `Petteri.Aimonen` on 13 Dec 2012 at 7:42

**Comment by kamathba** [comment]
I think the C++ wrapper interface could be useful and not super tricky to write (though to be honest I don't know as much as I'd like about c++). Here is a proposal that takes advantage of polymorphism and c++11 defined POD structs that could work depending on what you are trying to preserve.

In the C++ interface, define a Message struct or class that has all the encode/decode functions with an identical API minus the struct message_type* pointer (could maybe add some helper functions to this). These would call the c versions of the functions using the void* to *this* instead of passing in the struct src/dst. In essence, Message becomes a wrapper class for the c interface, or an abstract base class. Normally this is done by some virtual func() = 0, which forces an implementation, but having a protected destructor might work too. You *might* be able to declare the constructor on a per-message basis in the right conditions and using initializer lists. 

In the FooBar.pb.cc/h file you could define all the messages inheriting from the base Message type, with potentially additional helper functions (setters/getters), and maybe some friendly encode/decode functions (different name, no virtual functions but rather call parent function version of function with hard-coded fields array). You would now have some encode/decode functions that only require a stream input.

The members should all be generated as they would for the c-struct, and either all be public/private/protected. Note also that the c++ MessageType_struct should be declared final if you wanted the structures in-memory format to be the same. Can also have static asserts that the sizeof(c++_struct) == sizeof(c_struct) in that case. You could probably achieve a bit more flexibility on some of these "rules" if preserving the in-memory data format were not a goal.

I'm not thinking of everything, and am not even sure if I'm addressing the concerns of maintaining two languages of the library, but this method would rely entirely on the existing nanopb c modules to implement protocol buffers. Additionally, it could extend nanopb to work more simply with some of the new protobuf features, including rpc services, and other features I'm not thinking of. Feel free to shoot this down if you have a better understanding of c++, as I stick mostly to c :)

**Comment by PetteriAimonen** [comment]
Indeed I would like an approach that is not very heavy-weight,
so that maintaining the C++ interface will not be a burden. If
I understand your suggestion correctly, this might be simple
enough.

Could it be done like this?

pb_cxx.h/cxx: Definition of Message base class and any other necessary 
C++ stuff.

myproto.pb.h/c: Same as with C version. There would just be a macro in
struct MyMessage PB_CXX_INHERIT { .. } to provide the inheritance for
C++, and #ifdefs for anything else C++ specific.

It would be great if there is no need to have different generator output
for C++.

**Comment by kamathba** [comment]
Yes, I believe that could work. I have another pattern in mind that would let you do something like

// in Message.pb.hpp file (c++ header)
#include "pb_cxx.h"
#include "Message.pb.h" // shouldn't need to force c linkage, no functions to mangle

// note that MessageCppType and MessageCType should be identical in memory according to the c++11 spec *I think*
struct MessageCppType : public BaseMessage, public MessageCType {
    // Only need to define helper functions, maybe a constructor, all member data provided by MessageCType
}

This way your application could use either/or/both the c/c++ interfaces rather easily, and the generated c files wouldn't get cluttered. I do see the appeal of containing them all in one place though. I think both could work, and will think on it for a bit.

**Comment by kamathba** [comment]
don't have to use multiple inheritance necessarily either. could declare an instance of the C struct instead

**Comment by dsblue** [comment]
Kamathba,  I saw that you mentioned the idea of adding RPC/Services to nanopb.  Do you have a branch or patch that supports service entries?  I would love to port some code to nanopb, but it uses service rpc structures.  I'm looking for a workaround/path to supporting it on nanopb.

**Comment by PetteriAimonen** [comment]
@dsblue Just out of interest, which RPC implementation have you used before?

**Comment by dsblue** [comment]
I can't vouch for it yet, but I am currently playing with the protobuf-c-rpc under Linux. 
https://github.com/protobuf-c/protobuf-c-rpc

**Comment by eric-wieser** [comment]
Something else that would be handy would be if the `MyClassName_fields` variable were available as `MyClassName::fields`, so that you could write a template like

```c++
template<typename T>
bool pb_encode_submessage(pb_ostream_t *s, T *msg) {
    return pb_encode_submessage(s, T::fields, msg);
}
```

**Comment by eric-wieser** [comment]
Or perhaps in general, every `#define MyType_something` in the header would map to `static const  pb_traits<MyType>::something;`

**Comment by stream-jpa** [comment]
@kamathba I'm also for namespaced approach. Assume your `MessageCType` is for an example `PackageName_Foo_Bar`. Then `Message.pb.hpp` struct could look like

```
namespace PackageName {
    namespace Foo {
        struct Bar : /* public BaseMessage,*/ public PackageName_Foo_Bar { 
            /* setters, getters, isSetAttrname stuff */
        }
    }
}
```

@PetteriAimonen namespaces could help to write less code in C++, even the C++ generated helper interface with no setters/getters like

```
namespace PackageName {
    namespace Foo {
        typedef PackageName_Foo_Bar Bar;
    }
}
```
have value I think.

**Comment by eric-wieser** [comment]
> /* setters, getters, isSetAttrname stuff */

Why do we need any of these? Setters and getters just seem like extra code size with no benefit, and `isSetAttrname` is not really supported in proto3 anyway.

**Comment by PetteriAimonen** [comment]
To keep the scope from expanding too much, I've decided that nanopb is better off as a C-only library. A lightweight C++-based library is a good idea, but that should probably be an entirely separate project.
