### ISSUE TITLE
How to read/set optional fields

### ISSUE THREAD

**Issue by danielbuechele** [nanopb/nanopb#689]
Sorry, this question might be a noob question: I'm using optional fields from proto3, which for `optional list_id` generate this output:

```
pb_size_t which__list_id;
union {
    int32_t list_id;
} _list_id; 
```

How can I:
* check if the field is set
* read the value
* set the value

**Comment by PetteriAimonen** [comment]
Looks like you are getting the backwards compatibility oneof generated by `protoc`. With it you would set `msg.which__list_id` to `msg_list_id_tag` if it is present or 0 if not present. The value you would access as `msg._list_id.list_id`.

Since nanopb 0.4.4 there is also direct support for proto3 `optional` fields. I'm not sure if it is still needed to pass `--experimental_allow_proto3_optional` flag to `protoc` to enable it or not. There is a test case for it in https://github.com/nanopb/nanopb/tree/master/tests/proto3_optional
