### ISSUE TITLE
looking for PlatformIO example project - VS Code/Platformi/nanopb

### ISSUE THREAD

**Issue by mhaberler** [nanopb/nanopb#711]
Hi,

I want to use nanopb under VS Code and Platformio

I'm looking for an example project for this combo which uses nanopb and has the necessary magic included to compile proto files 

there is a ton of extensions for protobuf/VS Code and I am at loss which one would be a solid starting point

thanks in advance,
Michael

**Comment by mhaberler** [comment]
aha, the vscode-proto3 has some support for "Compile this Proto" and "Compile All Protos" (search for "proto" after command-shift-p)
trying the former gives me a "Missing output directives" 

it looks like one has to add this magic to .vscode/settings.json: https://github.com/zxh0/vscode-proto3/blob/master/example/.vscode/settings.json

**Comment by PetteriAimonen** [comment]
Maybe! It would at least be interesting to have one in the issue attachments, even if it ends up being too specific to include in the main codebase.

**Comment by mhaberler** [comment]
yeah, separate repo would be the way to go as it is easier importing into Platformio and it's own directory structure

seems[ people are having this issue since 2015...]( people are having this issue since 2015...)

**Comment by mhaberler** [comment]
duh, my bad - it's been a while

I was trying to get away with just installing the [Platformio nanopb library](https://platformio.org/lib/show/431/Nanopb/examples) and assumed a matching protoc-gen-nanopb would ride along 

however, this library only exports *.c *.h *.cpp examples, so no - no protoc-gen-nanopb, so that is good only for already generated .pb.h/.pb.c files 

what is the suggested way to get at protoc-gen-nanopb in this case?

I could ether forget about the PlatformIO library, add https://github.com/nanopb/nanopb as a submodule under lib/ and call the generator like under [Generating the headers](https://github.com/nanopb/nanopb#generating-the-headers) for source checkout by adding the right incantation to settings.json

or I could brew/conda etc install a nanopb package which has the generator and call that from settings.json

but in the latter case a separate step is needed outside VScode and I see the danger of the library and nanopb_generator.py diverging

what would you suggest?

**Comment by ivankravets** [comment]
@mhaberler yes, this is exactly what I meant. 

Happy coding with PlatformIO!

**Comment by PetteriAimonen** [comment]
There is https://github.com/nanopb/nanopb/blob/master/tests/site_scons/site_tools/nanopb.py as nanopb's own test system uses SCons also.

So something like this could work:

     env.Tool("nanopb", toolpath = ["lib/nanopb/tests/site_scons/site_tools"])
     env.NanopbProto("foo.proto")

**Comment by mhaberler** [comment]
yep, [there are gotchas](https://github.com/mhaberler/nanopb-test/commit/5d4a225871f764741e77feba4fc069fc2bcfd8a0) ;)

the brute-force solution is good enough for government work, and my purposes for now

**Comment by PetteriAimonen** [comment]
With 0.4.6 published the above fixes are included.

As for determining the generator path from platformio - I don't know, I'm very much a platformio novice myself :)

**Comment by Ma-Pe-Ma** [comment]
Hello!

Before getting to the problem, I have to state that I'm a beginner with both PlatformIO and SCons so I might totally misunderstand key concepts.

I cloned @mhaberler's [test repo](https://github.com/mhaberler/nanopb-test) which was mentioned in the earlier comments. However I added the `nanopb` project  as a git submodule in the `libs` directory instead of specifying it in the `platformio.ini`'s `lib_deps` section (PlatformIO finds `nanopb` this way, I'm sure about this).

So basically I want to compile the .proto file automatically before building the project, but the proto file's compilation does not happen.

I see that in the [custom script](https://github.com/mhaberler/nanopb-test/blob/master/scripts/rebuild-nanopb-scons.py) the compilation process is added as a custom target but its action does not get called during the building process.

I tried to manually add this new custom target to the `platformio.ini`'s target section:

    targets = nanopb-scons
 
In this case if I launch the build process then the `nanopb_callback` gets called, it runs without errors, it finds and runs the `NanopbProto` method but it does not generate the proper `.pb.h` and `.pb.c` sources. Then the build process is marked as success and it isn't even attempted to build the project sources (which would of course fail as the generated files would be missing).

I also tried to add a pre-action in the script file without success:

    env.AddPreAction("buildprog", nanopb_callback)

So what am I missing and how can my problem be solved?

**Comment by mhaberler** [comment]
Hi Péter

that's from way back - things have become much simpler nowadays

have a look at this repo: https://github.com/mhaberler/nimble-bl5-examples/blob/protobuf/platformio.ini

just fork, checkout the protobuf branch and build it - it has all the nanopb moving parts addressed

**Comment by Ma-Pe-Ma** [comment]
Hi Michael!

Thanks for the incredibly fast response!

Wow, this new approach is indeed much simpler and works without any problems, thank you for your help!
