### ISSUE TITLE
Usage of STRIP causes error as if ${NANOPB_PLUGIN_OPTIONS} is empty

### ISSUE THREAD

**Issue by philam2001** [nanopb/nanopb#973]
Noticed an issue with a codebase that uses nanopb that I'm working on with the new update because of this STRIP command. I researched it a little bit, it seems like if the ${NANOPB_PLUGIN_OPTIONS} that is part of the arguments in the STRIP command is empty, this can cause issues for the command to only see one argument. A thing that could be added is a check to see if the option is empty or not, another thing is to put quotation marks on the variable. If this is deemed a legitimate issue I could also put up a PR myself, I don't really know how contributions to open source codebases work. I would just be changing 
`string(STRIP ${NANOPB_PLUGIN_OPTIONS} NANOPB_PLUGIN_OPTIONS)`
to this
`string(STRIP "${NANOPB_PLUGIN_OPTIONS}" NANOPB_PLUGIN_OPTIONS)`
which I believe should resolve the issue seen.

**Comment by PetteriAimonen** [comment]
@gsurkov Any thoughts?

**Comment by gsurkov** [comment]
I think that surrounding the variable in quotation marks is the way to go because not only it fixes the problem, it can also prevent other potential bugs. And I'm pretty sure the STRIP command does the check for empty string internally.

Changes are proposed in #974, sorry for the inconvenience my changes have caused.

**Comment by philam2001** [comment]
No worries, looks good!
